version: 2.1

orbs:
  kaocha: lambdaisland/kaocha@0.0.3
  clojure: lambdaisland/clojure@0.0.8

jobs:
  test:
    parameters:
      os:
        type: executor
      clojure_version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - clojure/with_cache:
          cache_version: << parameters.clojure_version >>
          steps:
            - run: clojure -e '(println (System/getProperty "java.runtime.name") (System/getProperty "java.runtime.version") "\nClojure" (clojure-version))'
            - kaocha/execute:
                args: "unit --reporter documentation --plugin cloverage --codecov"
                clojure_version: << parameters.clojure_version >>
            - kaocha/upload_codecov:
                flags: unit

workflows:
  kaocha_test:
    jobs:
      - test:
          matrix:
            parameters:
              os: [clojure/openjdk17, clojure/openjdk11, clojure/openjdk8]
              clojure_version: ["1.9.0", "1.10.3", "1.11.1"]
